CREATE TABLE IF NOT EXISTS USER (
  id    INTEGER PRIMARY KEY AUTOINCREMENT,
  name  TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS COURSE (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id     INTEGER,
  name        TEXT NOT NULL,
  description TEXT,
  FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TASK (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id  INTEGER,
  name       TEXT NOT NULL,
  description TEXT,
  due_date    TEXT,
  FOREIGN KEY (course_id) REFERENCES COURSE (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COURSE_SCHEDULE (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id    INTEGER NOT NULL,
  course_id  INTEGER NOT NULL,
  day        INTEGER NOT NULL,      -- 0 = Mon, 1 = Tue, ... 6 = Sun
  start_time TEXT NOT NULL,         -- "HH:MM"
  end_time   TEXT NOT NULL,         -- "HH:MM"
  FOREIGN KEY (user_id)   REFERENCES USER (id)   ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES COURSE (id) ON DELETE CASCADE
);

